package apresentacao;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.NoResultException;
import javax.persistence.Query;
import javax.swing.JTable;
import modelo.Pedido;
import servico.ClienteDAO;

/**
 *
 * @author Magalhães Oliveira
 */
public class frmRelPPC extends javax.swing.JFrame {

    private List<Pedido> tbPedidoCliente;
    private Query tbPedidoQueryCliente;
    private JTable pedidoscliente;
    
    /**
     * Creates new form frmRelPPC
     */
    public frmRelPPC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ControleVendasEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("ControleVendas").createEntityManager();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cliente = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        pedidoscliente = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Pedidos Feitos por Cliente Específico");

        jLabel2.setText("Cliente: ");


        cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(61, 61, 61)
                        .addComponent(cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );


        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteActionPerformed
        tbPedidoQueryCliente = ControleVendasEntityManager.createQuery("SELECT t FROM Pedido t WHERE t.cliente = :cliente");
        tbPedidoQueryCliente.setParameter("cliente",new ClienteDAO().getIdPorNome(cliente.getSelectedItem().toString()));
        
        tbPedidoCliente = new ArrayList<>();
        
        try{
            tbPedidoCliente = tbPedidoQueryCliente.getResultList();
        }catch(NoResultException e){
            
        }
        
        /*
        String[] tableColumnsName = {"ID", "DATA", "FUNCIONARIO", "TOTAL"};
        DefaultTableModel aModel = new DefaultTableModel();
        aModel.setColumnIdentifiers(tableColumnsName); // query
        
        int i = 0;
        
        while (i < tbPedidoList.size()) {
            Object[] objects = new Object[i];
            for (int j = 0; j <= 3; j++) {
                objects[j] = tbPedidoList.get(j);
            }
            aModel.addRow(objects);
            i++;
        }

        pedidoscliente.setModel(aModel);
        */
    }//GEN-LAST:event_clienteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager ControleVendasEntityManager;
    private javax.swing.JComboBox cliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.persistence.EntityManager vendasPUEntityManager;
    // End of variables declaration//GEN-END:variables
}
