
package apresentacao;

import apresentacao.Consultas.frmConsCliente;
import apresentacao.Consultas.frmConsProdutos;
import apresentacao.Cadastros.JFrameProduto;
import apresentacao.Cadastros.JFrameCliente;
import apresentacao.Cadastros.JFrameFuncionario;
import apresentacao.Consultas.frmConsEntreDatas;
import apresentacao.Consultas.frmConsFuncionario;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author Magalhães Oliveira
 */
public class JFrameAplicacao extends javax.swing.JFrame {
    
    private BufferedImage img = null;    

    public JFrameAplicacao() throws IOException {
        super("GI Moto Peças");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Cadastros = new javax.swing.JMenu();
        Cliente = new javax.swing.JMenuItem();
        Funcionario = new javax.swing.JMenuItem();
        Produtos = new javax.swing.JMenuItem();
        atualizaProduto = new javax.swing.JMenuItem();
        Pedir = new javax.swing.JMenu();
        atendimento = new javax.swing.JMenuItem();
        pedido = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Consultas = new javax.swing.JMenu();
        consPessoas = new javax.swing.JMenuItem();
        funcionariosss = new javax.swing.JMenuItem();
        consProdutos = new javax.swing.JMenuItem();
        Relatorios = new javax.swing.JMenu();
        entreDatas = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        verPedidos = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kawa.jpg"))); // NOI18N

        jMenuBar1.setBackground(new java.awt.Color(204, 255, 204));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuBar1.setMinimumSize(new java.awt.Dimension(100, 5));

        Cadastros.setBackground(new java.awt.Color(204, 255, 204));
        Cadastros.setText("Cadastros");
        Cadastros.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        Cliente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Cliente.setText("Clientes");
        Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteActionPerformed(evt);
            }
        });
        Cadastros.add(Cliente);

        Funcionario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Funcionario.setText("Funcionarios");
        Funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FuncionarioActionPerformed(evt);
            }
        });
        Cadastros.add(Funcionario);

        Produtos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Produtos.setText("Produtos");
        Produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdutosActionPerformed(evt);
            }
        });
        Cadastros.add(Produtos);

        atualizaProduto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        atualizaProduto.setText("Atualiza Produto");
        atualizaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizaProdutoActionPerformed(evt);
            }
        });
        Cadastros.add(atualizaProduto);

        jMenuBar1.add(Cadastros);

        Pedir.setBackground(new java.awt.Color(255, 255, 204));
        Pedir.setText("Pedidos");
        Pedir.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        atendimento.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        atendimento.setText("Atendimento Inicial");
        atendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atendimentoActionPerformed(evt);
            }
        });
        Pedir.add(atendimento);

        pedido.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        pedido.setText("Novo Pedido");
        pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedidoActionPerformed(evt);
            }
        });
        Pedir.add(pedido);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 0));
        Pedir.add(jSeparator1);

        jMenuBar1.add(Pedir);

        Consultas.setText("Consultas");
        Consultas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        consPessoas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        consPessoas.setText("Clientes");
        consPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consPessoasActionPerformed(evt);
            }
        });
        Consultas.add(consPessoas);

        funcionariosss.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        funcionariosss.setText("Funcionarios");
        funcionariosss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcionariosssActionPerformed(evt);
            }
        });
        Consultas.add(funcionariosss);

        consProdutos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        consProdutos.setText("Produtos");
        consProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consProdutosActionPerformed(evt);
            }
        });
        Consultas.add(consProdutos);

        jMenuBar1.add(Consultas);

        Relatorios.setText("Relatórios");
        Relatorios.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        entreDatas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        entreDatas.setText("Pedidos entre Datas");
        entreDatas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entreDatasActionPerformed(evt);
            }
        });
        Relatorios.add(entreDatas);

        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItem4.setText("Pedidos por Cliente");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        Relatorios.add(jMenuItem4);

        verPedidos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        verPedidos.setText("Ver Pedidos");
        verPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verPedidosActionPerformed(evt);
            }
        });
        Relatorios.add(verPedidos);

        jMenuBar1.add(Relatorios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteActionPerformed
        JFrameCliente jFrameCliente = new JFrameCliente();
        jFrameCliente.setLocationRelativeTo(null);
        jFrameCliente.setVisible(true);
    }//GEN-LAST:event_ClienteActionPerformed

    private void FuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FuncionarioActionPerformed
        JFrameFuncionario jFrameFuncionario = new JFrameFuncionario();
        jFrameFuncionario.setLocationRelativeTo(null);
        jFrameFuncionario.setVisible(true);
    }//GEN-LAST:event_FuncionarioActionPerformed

    private void ProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdutosActionPerformed
        JFrameProduto jFrameProduto = new JFrameProduto();
        jFrameProduto.setLocationRelativeTo(null);
        jFrameProduto.setVisible(true);
    }//GEN-LAST:event_ProdutosActionPerformed

    private void pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedidoActionPerformed
        frmNovoPedido frm = new frmNovoPedido();
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
    }//GEN-LAST:event_pedidoActionPerformed

    private void consPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consPessoasActionPerformed
        frmConsCliente frm = new frmConsCliente();
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
    }//GEN-LAST:event_consPessoasActionPerformed

    private void consProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consProdutosActionPerformed
        frmConsProdutos frm = new frmConsProdutos();
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
    }//GEN-LAST:event_consProdutosActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        frmRelPPC frm = new frmRelPPC();
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void verPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verPedidosActionPerformed
        frmVerPedidos frm = new frmVerPedidos();
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
    }//GEN-LAST:event_verPedidosActionPerformed

    private void atendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atendimentoActionPerformed
            // Chamar tela a ser implementada
    }//GEN-LAST:event_atendimentoActionPerformed

    private void funcionariosssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcionariosssActionPerformed
        frmConsFuncionario frm = new frmConsFuncionario();
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
    }//GEN-LAST:event_funcionariosssActionPerformed

    private void entreDatasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entreDatasActionPerformed
        frmConsEntreDatas frm = new frmConsEntreDatas();
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
    }//GEN-LAST:event_entreDatasActionPerformed

    private void atualizaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizaProdutoActionPerformed
        frmAtualizaProduto frm = new frmAtualizaProduto();
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
    }//GEN-LAST:event_atualizaProdutoActionPerformed

    @Override  
    public void paintComponents(Graphics g) { 
        super.paintComponents(g);        
        Graphics gr = (Graphics2D)g.create();
        //gr.drawImage(img, 0, 0, null);
        gr.drawImage(this.img,this.getWidth(),this.getHeight(),this);  
        gr.dispose();     
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Cadastros;
    private javax.swing.JMenuItem Cliente;
    private javax.swing.JMenu Consultas;
    private javax.swing.JMenuItem Funcionario;
    private javax.swing.JMenu Pedir;
    private javax.swing.JMenuItem Produtos;
    private javax.swing.JMenu Relatorios;
    private javax.swing.JMenuItem atendimento;
    private javax.swing.JMenuItem atualizaProduto;
    private javax.swing.JMenuItem consPessoas;
    private javax.swing.JMenuItem consProdutos;
    private javax.swing.JMenuItem entreDatas;
    private javax.swing.JMenuItem funcionariosss;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem pedido;
    private javax.swing.JMenuItem verPedidos;
    // End of variables declaration//GEN-END:variables
}
